import { MemberShell } from "@/components/MemberShell";
import { Button } from "@/components/ui/button";
import { ArrowRight, BookOpen, Check, ChefHat, Compass, Sparkles, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const benefits = [
  { icon: ChefHat, title: "Biblioteca de receitas", text: "Receitas completas para diferentes momentos da rotina." },
  { icon: Sparkles, title: "Novos conteúdos", text: "Novas possibilidades para descobrir e experimentar." },
  { icon: Compass, title: "Academia Atípica", text: "Caminhos organizados para transformar informação em repertório." },
  { icon: UsersRound, title: "Comunidade", text: "Trocas, perguntas e pertencimento com outras famílias." },
  { icon: BookOpen, title: "Guias complementares", text: "Materiais de apoio para voltar sempre que precisar." },
];

export default function Assinatura() {
  const [, setLocation] = useLocation();

  return <MemberShell allowGuest eyebrow="Universo Atípico" title="Mais possibilidades para a sua rotina." description="Receitas, jornadas e conteúdos para descobrir caminhos que façam sentido para cada família.">
    <section className="relative overflow-hidden rounded-[2rem] bg-[var(--sage-deep)] p-7 text-white sm:p-10 lg:p-12"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border border-white/10" /><div className="relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#efd4a2]"><Sparkles size={13} /> Acesso completo</span><h2 className="display-font mt-6 max-w-3xl text-4xl font-semibold leading-[0.94] sm:text-6xl">Seu espaço para descobrir receitas e novas possibilidades.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/75 sm:text-base">Um Universo pensado para acompanhar a vida real: comida possível, jornadas que respeitam o ritmo e uma comunidade para caminhar junto.</p></div><div className="rounded-3xl bg-white p-6 text-[var(--ink)] shadow-2xl lg:w-80"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[var(--sage)]">Plano Universo</p><p className="display-font mt-4 text-5xl font-semibold">R$ 49,90</p><p className="mt-1 text-sm font-bold text-[var(--ink-soft)]">por mês</p><div className="mt-6 space-y-3">{benefits.slice(0, 3).map(item => <div key={item.title} className="flex items-start gap-2 text-xs font-bold"><Check size={15} className="mt-0.5 shrink-0 text-[var(--sage)]" />{item.title}</div>)}</div><Button type="button" onClick={() => setLocation("/checkout")} className="pressable mt-7 w-full rounded-xl bg-[var(--sage-deep)] text-xs font-extrabold text-white hover:bg-[var(--ink)]">Quero fazer parte <ArrowRight size={14} className="ml-2" /></Button><p className="mt-3 text-center text-[10px] font-semibold text-[var(--ink-soft)]">Cobrança ainda não ativada.</p></div></div></section>
    <section className="mt-12"><div className="mb-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[var(--sage)]">O que está incluído</p><h2 className="display-font mt-2 text-3xl font-semibold">Uma experiência, não apenas arquivos.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(item => { const Icon = item.icon; return <article key={item.title} className="rounded-3xl border border-[var(--line)] bg-white p-6 shadow-[0_10px_24px_rgba(8,31,77,.04)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--sage-pale)] text-[var(--sage-deep)]"><Icon size={19} /></span><h3 className="display-font mt-5 text-2xl font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--ink-soft)]">{item.text}</p></article>; })}</div></section>
    <section className="mt-12 rounded-3xl bg-[var(--linen)] p-7 sm:p-9"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[var(--clay)]">Para começar agora</p><h2 className="display-font mt-3 max-w-2xl text-3xl font-semibold leading-tight">Explore a biblioteca e as receitas incluídas na sua assinatura.</h2><div className="mt-6 flex flex-wrap gap-3"><Button type="button" onClick={() => setLocation("/biblioteca")} className="pressable rounded-xl bg-[var(--sage-deep)] text-xs font-extrabold text-white hover:bg-[var(--ink)]">Ver a biblioteca <ArrowRight size={14} className="ml-2" /></Button><Button type="button" variant="outline" onClick={() => setLocation("/receitas")} className="pressable rounded-xl border-[var(--line)] bg-white text-xs font-extrabold text-[var(--sage-deep)]">Explorar receitas <ChefHat size={14} className="ml-2" /></Button></div></section>
  </MemberShell>;
}
