import { ContentEmpty, MemberShell, SectionHeading } from "@/components/MemberShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ArrowUpRight, BookOpen, FileDown, GraduationCap, Lightbulb, MessageCircleMore, ShoppingBag, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

function formatDate(value: Date | string | null) {
  if (!value) return "Disponível agora";
  return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
}

export default function Community() {
  const dashboard = trpc.community.memberDashboard.useQuery();
  const recipeShelf = trpc.community.publicAcademiaGuides.useQuery();
  const [downloading, setDownloading] = useState<number | null>(null);
  const data = dashboard.data;
  const firstGuide = data?.guides.find(guide => guide.hasPdf);
  const readingProgress = trpc.community.readingProgress.get.useQuery({ sourceType: "guide", documentId: Math.max(1, firstGuide?.id ?? 0) }, { enabled: Boolean(firstGuide) });
  const progressPercent = readingProgress.data?.pageCount ? Math.min(100, Math.round((readingProgress.data.currentPage / readingProgress.data.pageCount) * 100)) : 0;
  const recipesForYou = (recipeShelf.data || []).filter(guide => guide.category.toLocaleLowerCase("pt-BR").includes("aliment")).slice(0, 3);

  if (dashboard.isLoading) {
    return <MemberShell eyebrow="Minha área" title="Seu espaço na comunidade" description="Estamos reunindo seus conteúdos e conversas."><div className="space-y-8"><div className="grid gap-4 md:grid-cols-3"><div className="h-52 animate-pulse rounded-3xl bg-[var(--linen)] md:col-span-2" /><div className="h-52 animate-pulse rounded-3xl bg-[var(--linen)]" /></div><div className="h-8 w-48 animate-pulse rounded-full bg-[var(--linen)]" /><div className="grid gap-4 md:grid-cols-2"><div className="h-60 animate-pulse rounded-3xl bg-[var(--linen)]" /><div className="h-60 animate-pulse rounded-3xl bg-[var(--linen)]" /></div></div></MemberShell>;
  }

  if (dashboard.isError) {
    return <MemberShell eyebrow="Minha área" title="Seu espaço na comunidade" description="Não foi possível abrir seus conteúdos neste momento."><ContentEmpty title="Não conseguimos carregar sua área" text="Verifique sua conexão e tente atualizar a página. Se o problema persistir, volte mais tarde." /></MemberShell>;
  }

  const downloadGuide = (guideId: number) => {
    setDownloading(guideId);
    window.location.href = `/biblioteca?guide=${guideId}`;
  };

  return <MemberShell eyebrow="Minha área" title={`Olá${data?.profile?.displayName ? `, ${data.profile.displayName.split(" ")[0]}` : ""}.`} description="Aqui você encontra os conteúdos liberados, recursos selecionados e as conversas recentes da comunidade.">
    <section className="mb-12 grid gap-4 md:grid-cols-3"><div className="relative overflow-hidden rounded-3xl bg-[var(--sage-deep)] p-6 text-white md:col-span-2"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full border border-white/20" /><Sparkles size={19} className="text-[#f2d4a1]" /><p className="mt-8 text-xs font-extrabold uppercase tracking-[0.16em] text-white/70">Tudo em um só lugar</p><h2 className="display-font mt-3 max-w-xl text-4xl font-semibold leading-[0.95]">Um espaço para descobrir receitas e possibilidades para a rotina real.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/75">Explore os materiais disponíveis e participe no seu próprio ritmo.</p></div><div className="soft-card rounded-3xl p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[var(--sage)]">Seu acesso</p><p className="display-font mt-5 text-4xl font-semibold">Membros</p><p className="mt-2 text-sm leading-6 text-[var(--ink-soft)]">Receitas, jornadas e conteúdos para acompanhar sua família.</p></div></section>

    <section className="mb-8 rounded-3xl border border-[var(--line)] bg-white p-6 shadow-[0_10px_24px_rgba(8,31,77,.04)] sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[var(--clay-pale)] text-[var(--clay)]"><BookOpen size={19} /></span><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[var(--clay)]">Continue de onde parou</p><h2 className="display-font mt-2 text-2xl font-semibold leading-tight">{readingProgress.data?.currentPage && firstGuide ? firstGuide.title : firstGuide ? `Comece por ${firstGuide.title}` : "Escolha uma leitura para começar"}</h2><p className="mt-2 text-sm leading-6 text-[var(--ink-soft)]">{readingProgress.data?.currentPage && firstGuide ? `Você está na página ${readingProgress.data.currentPage} de ${readingProgress.data.pageCount}.` : "Retome seus guias sempre que quiser, no seu próprio ritmo."}</p></div></div><div className="flex items-center gap-4 sm:min-w-56"><div className="min-w-0 flex-1"><div className="mb-2 flex justify-between text-[10px] font-extrabold uppercase tracking-[0.14em] text-[var(--ink-soft)]"><span>Progresso</span><span>{progressPercent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[var(--linen)]" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progressPercent} aria-label={`Progresso da leitura: ${progressPercent}%`}><div className="h-full rounded-full bg-[var(--clay)] transition-[width] duration-300" style={{ width: `${progressPercent}%` }} /></div></div>{firstGuide ? <Link href={`/biblioteca?guide=${firstGuide.id}`} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[var(--sage-deep)] text-white transition hover:bg-[var(--ink)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--sage)]" aria-label={readingProgress.data?.currentPage ? "Continuar leitura" : "Começar leitura"}><ArrowRight size={18} /></Link> : null}</div></div></section>

    <section className="mb-14"><SectionHeading label="Receitas para você" title="Possibilidades para experimentar." action={<Link href="/receitas" className="inline-flex items-center gap-2 text-xs font-extrabold text-[var(--sage-deep)]">Ver todas <ArrowRight size={14} /></Link>} />{recipesForYou.length ? <div className="grid gap-4 md:grid-cols-3">{recipesForYou.map(recipe => <Link key={recipe.id} href={`/receitas`} className="group overflow-hidden rounded-3xl border border-[var(--line)] bg-white shadow-[0_10px_24px_rgba(8,31,77,.04)] transition hover:-translate-y-0.5 hover:shadow-[0_16px_30px_rgba(8,31,77,.1)]"><div className="relative h-36" style={{ backgroundColor: recipe.accentColor }}>{recipe.coverImageUrl ? <img src={recipe.coverImageUrl} alt={`Capa de ${recipe.title}`} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]" /> : <div className="quiet-grid grid h-full place-items-center text-white/75"><BookOpen size={32} /></div>}<span className="absolute left-3 top-3 rounded-full bg-[var(--ink)]/90 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[0.13em] text-white">Membros</span></div><div className="p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[var(--sage)]">{recipe.category}</p><h3 className="display-font mt-2 text-2xl font-semibold leading-tight">{recipe.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--ink-soft)]">{recipe.summary}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold text-[var(--sage-deep)]">Conhecer receita <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div> : <ContentEmpty icon={BookOpen} title="Novas receitas em breve" text="As próximas possibilidades para sua rotina aparecerão aqui." />}</section>

    <section className="mb-14"><SectionHeading label="Explore o universo" title="Encontre seu próximo caminho." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ href: "/biblioteca", icon: BookOpen, label: "Biblioteca", text: "Guias para consultar no seu ritmo." }, { href: "/academia", icon: GraduationCap, label: "Academia Atípica", text: "Conteúdos para aprender e praticar." }, { href: "/forum", icon: MessageCircleMore, label: "Comunidade", text: "Conversas, perguntas e acolhimento." }, { href: "/facilitadores", icon: Lightbulb, label: "Facilitadores", text: "Referências para a rotina." }].map(item => { const Icon = item.icon; return <Link key={item.href} href={item.href} className="group rounded-3xl border border-[var(--line)] bg-white p-5 shadow-[0_10px_24px_rgba(8,31,77,.04)] transition hover:-translate-y-0.5 hover:border-[var(--blue)] hover:shadow-[0_16px_30px_rgba(8,31,77,.08)]"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[var(--sage-pale)] text-[var(--sage-deep)]"><Icon size={18} /></span><h3 className="mt-5 text-sm font-extrabold text-[var(--ink)]">{item.label}</h3><p className="mt-2 min-h-10 text-xs leading-5 text-[var(--ink-soft)]">{item.text}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold text-[var(--sage-deep)]">Explorar <ArrowRight size={14} className="transition-transform group-hover:translate-x-1" /></span></Link>; })}</div></section>

    <section className="mb-14"><SectionHeading label="Biblioteca" title="Guias liberados" action={<span className="hidden text-xs font-bold text-[var(--ink-soft)] sm:block">Conteúdos publicados pela administração</span>} />{dashboard.isLoading ? <div className="grid gap-4 md:grid-cols-2"><div className="h-52 animate-pulse rounded-3xl bg-[var(--linen)]" /><div className="h-52 animate-pulse rounded-3xl bg-[var(--linen)]" /></div> : data?.guides?.length ? <div className="grid gap-4 md:grid-cols-2">{data.guides.map(guide => <article key={guide.id} className="soft-card relative overflow-hidden rounded-3xl p-6"><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-[4rem] bg-[var(--sage-pale)]" /><span className="relative inline-flex rounded-full bg-[var(--sage-pale)] px-3 py-1 text-[10px] font-extrabold uppercase tracking-[0.14em] text-[var(--sage-deep)]">{guide.category}</span><h3 className="display-font relative mt-5 text-3xl font-semibold leading-[0.98]">{guide.title}</h3><p className="relative mt-4 line-clamp-3 text-sm leading-6 text-[var(--ink-soft)]">{guide.summary}</p><div className="relative mt-6 flex items-center justify-between gap-3"><span className="text-xs font-bold text-[var(--ink-soft)]">{formatDate(guide.publishedAt || guide.createdAt)}</span>{guide.hasPdf ? <Button variant="outline" onClick={() => downloadGuide(guide.id)} disabled={downloading === guide.id} className="pressable rounded-xl border-[var(--line)] bg-white text-xs font-extrabold text-[var(--sage-deep)]"><FileDown size={15} className="mr-2" />{downloading === guide.id ? "Abrindo..." : "Ler dentro da plataforma"}</Button> : <span className="text-xs font-bold text-[var(--ink-soft)]">Leitura em breve</span>}</div></article>)}</div> : <ContentEmpty icon={BookOpen} title="A biblioteca está sendo preparada" text="Assim que a administração publicar um guia, ele ficará disponível aqui para todos os membros." />}</section>

    <section className="mb-14"><SectionHeading label="Seleção" title="Facilitadores para a rotina" />{data?.facilitators?.length ? <div className="grid gap-4 md:grid-cols-3">{data.facilitators.map(item => <article key={item.id} className="soft-card flex min-h-64 flex-col rounded-3xl p-6"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--lavender)] text-[var(--sage-deep)]"><Lightbulb size={19} /></span><span className="mt-5 text-[10px] font-extrabold uppercase tracking-[0.15em] text-[var(--sage)]">{item.category}</span><h3 className="display-font mt-2 text-2xl font-semibold leading-none">{item.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[var(--ink-soft)]">{item.summary}</p>{item.linkUrl ? <a href={item.linkUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-[var(--sage-deep)] hover:underline">{item.sourceLabel || "Conhecer recurso"} <ArrowUpRight size={14} /></a> : null}</article>)}</div> : <ContentEmpty icon={Lightbulb} title="A seleção ainda vai ganhar vida" text="Os facilitadores publicados pela administração aparecerão aqui como referências organizadas para a rotina." />}</section>

    <section className="mb-14"><SectionHeading label="Recomendações" title="Seleções da plataforma" /><p className="-mt-3 mb-6 max-w-2xl text-sm leading-6 text-[var(--ink-soft)]">Quando uma recomendação levar a uma página externa, isso será informado antes do acesso. A comunidade permanece gratuita.</p>{data?.products?.length ? <div className="grid gap-4 md:grid-cols-3">{data.products.map(product => <article key={product.id} className="soft-card flex min-h-64 flex-col overflow-hidden rounded-3xl p-6"><div className="-mx-6 -mt-6 mb-5 h-24 bg-[var(--sage-pale)]">{product.coverImageUrl ? <img src={product.coverImageUrl} alt="" className="h-full w-full object-cover" /> : <div className="quiet-grid h-full" />}</div><span className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[var(--sage)]">{product.category}</span><h3 className="display-font mt-2 text-2xl font-semibold leading-none">{product.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[var(--ink-soft)]">{product.summary}</p><Link href={`/produto/${product.slug}?origem=client`} className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-[var(--sage-deep)] hover:underline">Conhecer recomendação <ArrowUpRight size={14} /></Link></article>)}</div> : <ContentEmpty icon={ShoppingBag} title="Ainda não há recomendações publicadas" text="Quando o Admin Master publicar uma seleção, ela aparecerá aqui de forma identificada e complementar." />}</section>

    <section><SectionHeading label="Comunidade" title="Conversas recentes" action={<Link href="/forum" className="text-sm font-extrabold text-[var(--sage-deep)] hover:underline">Ver todas</Link>} />{data?.recentTopics?.length ? <div className="overflow-hidden rounded-3xl border border-[var(--line)] bg-white">{data.recentTopics.map(topic => <Link key={topic.id} href={`/forum?topic=${topic.id}`} className="nav-link flex items-center justify-between gap-5 border-b border-[var(--line)] p-5 last:border-b-0 hover:bg-[var(--paper)]"><div className="min-w-0"><span className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[var(--sage)]">{topic.category}</span><h3 className="mt-1 truncate text-sm font-extrabold">{topic.title}</h3><p className="mt-1 truncate text-xs text-[var(--ink-soft)]">Por {topic.authorDisplayName || topic.authorName || "Membro da comunidade"}</p></div><div className="flex shrink-0 items-center gap-2 text-xs font-bold text-[var(--ink-soft)]"><MessageCircleMore size={16} />{topic.commentCount}</div></Link>)}</div> : <ContentEmpty icon={MessageCircleMore} title="As conversas começam quando a comunidade chega" text="Você poderá abrir um tópico no fórum e acompanhar novas conversas assim que quiser participar." />}</section>
  </MemberShell>;
}
