import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ALL_PERMISSIONS, PERMISSION_LABELS, Permission } from "@shared/permissions";
import { Save, Trash2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AccessControlPanel({ users, currentUserId }: { users: Array<{ id: number; name: string | null; displayName?: string | null; email: string | null }>; currentUserId: number }) {
  const query = trpc.community.master.accessControl.useQuery();
  const utils = trpc.useUtils();
  const [editingId, setEditingId] = useState<number | undefined>();
  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [description, setDescription] = useState("");
  const [permissions, setPermissions] = useState<Permission[]>(["view_metrics"]);
  const save = trpc.community.master.saveAccessLevel.useMutation({ onSuccess: async () => { await query.refetch(); setEditingId(undefined); setName(""); setSlug(""); setDescription(""); setPermissions(["view_metrics"]); toast.success("Nível salvo."); }, onError: error => toast.error(error.message) });
  const remove = trpc.community.master.deleteAccessLevel.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("Nível removido."); }, onError: error => toast.error(error.message) });
  const assign = trpc.community.master.assignAccessLevel.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("Permissão atualizada."); }, onError: error => toast.error(error.message) });
  const startEdit = (level: NonNullable<typeof query.data>["levels"][number]) => { setEditingId(level.id); setName(level.name); setSlug(level.slug); setDescription(level.description || ""); setPermissions(level.permissions as Permission[]); };
  const assigned = (userId: number, levelId: number) => query.data?.assignments.some(item => item.userId === userId && item.accessLevelId === levelId) ?? false;
  return <div className="mt-8 space-y-6">
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
      <form onSubmit={event => { event.preventDefault(); save.mutate({ id: editingId, name, slug, description: description || null, permissions }); }} className="rounded-3xl border border-[var(--line)] bg-white p-6">
        <p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--sage)]">{editingId ? "Editar nível" : "Novo nível"}</p><h3 className="display-font mt-2 text-2xl font-semibold">Permissões customizadas</h3><p className="mt-2 text-sm leading-6 text-[var(--ink-soft)]">Combine somente os acessos necessários para cada função. O Admin Master continua protegido.</p>
        <div className="mt-5 space-y-4"><div><Label htmlFor="access-level-name">Nome</Label><Input id="access-level-name" required value={name} onChange={event => setName(event.target.value)} className="mt-2 h-11 rounded-xl" /></div><div><Label htmlFor="access-level-slug">Identificador</Label><Input id="access-level-slug" required pattern="[a-z0-9-]+" value={slug} onChange={event => setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-"))} className="mt-2 h-11 rounded-xl" /></div><div><Label htmlFor="access-level-description">Descrição</Label><Input id="access-level-description" value={description} onChange={event => setDescription(event.target.value)} className="mt-2 h-11 rounded-xl" /></div><div className="space-y-2"><Label>Permissões</Label>{ALL_PERMISSIONS.map(permission => <label key={permission} className="flex items-center gap-3 rounded-xl bg-[var(--linen)] px-3 py-2 text-sm font-semibold"><input type="checkbox" checked={permissions.includes(permission)} onChange={event => setPermissions(current => event.target.checked ? [...current, permission] : current.filter(item => item !== permission))} />{PERMISSION_LABELS[permission]}</label>)}</div><div className="flex gap-2"><Button disabled={save.isPending} className="pressable rounded-xl bg-[var(--sage-deep)] font-extrabold text-white"><Save size={16} className="mr-2" />Salvar nível</Button>{editingId ? <Button type="button" variant="outline" onClick={() => { setEditingId(undefined); setName(""); setSlug(""); setDescription(""); setPermissions(["view_metrics"]); }} className="rounded-xl">Cancelar</Button> : null}</div></div>
      </form>
      <section className="rounded-3xl border border-[var(--line)] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--sage)]">Níveis cadastrados</p><h3 className="display-font mt-2 text-2xl font-semibold">Acesso por função</h3></div><ShieldCheck className="text-[var(--sage-deep)]" size={22} /></div><div className="mt-5 space-y-3">{query.data?.levels.length ? query.data.levels.map(level => <article key={level.id} className="rounded-2xl border border-[var(--line)] bg-[var(--paper)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-extrabold">{level.name}</p><p className="mt-1 text-xs text-[var(--ink-soft)]">{level.description || "Sem descrição"}</p></div><div className="flex gap-1"><Button variant="outline" onClick={() => startEdit(level)} className="h-8 rounded-lg px-3 text-xs">Editar</Button><Button variant="outline" onClick={() => remove.mutate({ id: level.id })} className="h-8 rounded-lg px-3 text-xs text-red-700"><Trash2 size={14} /></Button></div></div><div className="mt-3 flex flex-wrap gap-1">{level.permissions.map(permission => <span key={permission} className="rounded-full bg-[var(--sage-pale)] px-2 py-1 text-[10px] font-bold text-[var(--sage-deep)]">{PERMISSION_LABELS[permission as Permission] || permission}</span>)}</div></article>) : <p className="rounded-2xl bg-[var(--linen)] p-4 text-sm text-[var(--ink-soft)]">Crie o primeiro nível customizado.</p>}</div></section>
    </div>
    <section className="rounded-3xl border border-[var(--line)] bg-white p-6"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[var(--sage)]">Atribuições</p><h3 className="display-font mt-2 text-2xl font-semibold">Quem pode fazer o quê</h3><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-[var(--line)] text-xs text-[var(--ink-soft)]"><th className="p-3">Usuário</th>{query.data?.levels.map(level => <th key={level.id} className="p-3">{level.name}</th>)}</tr></thead><tbody>{users.map(member => <tr key={member.id} className="border-b border-[var(--line)] last:border-0"><td className="p-3"><p className="font-extrabold">{member.displayName || member.name || "Conta sem nome"}</p><p className="text-xs text-[var(--ink-soft)]">{member.email || "Sem e-mail"}</p></td>{query.data?.levels.map(level => <td key={level.id} className="p-3"><input type="checkbox" checked={assigned(member.id, level.id)} disabled={member.id === currentUserId || assign.isPending} onChange={event => assign.mutate({ userId: member.id, accessLevelId: level.id, assigned: event.target.checked })} aria-label={`${level.name} para ${member.email || member.name || "usuário"}`} /></td>)}</tr>)}</tbody></table></div></section>
  </div>;
}
