/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as AcademiaAtipicaRouteImport } from './routes/academia-atipica'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AssinaturaECancelamentoRouteImport } from './routes/assinatura-e-cancelamento'
import { Route as AvisoDeResponsabilidadeRouteImport } from './routes/aviso-de-responsabilidade'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FacilitadoresRouteImport } from './routes/facilitadores'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as AcademiaModuloRouteImport } from './routes/academia_.$modulo'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ReceitasCategoriaRouteImport } from './routes/receitas_.$categoria'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicUaImageSplatRouteImport } from './routes/api/public/ua-image/$'
import { Route as ApiPublicUaVideoSplatRouteImport } from './routes/api/public/ua-video/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaAtipicaRoute = AcademiaAtipicaRouteImport.update({
  id: '/academia-atipica',
  path: '/academia-atipica',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaECancelamentoRoute = AssinaturaECancelamentoRouteImport.update({
  id: '/assinatura-e-cancelamento',
  path: '/assinatura-e-cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeResponsabilidadeRoute = AvisoDeResponsabilidadeRouteImport.update({
  id: '/aviso-de-responsabilidade',
  path: '/aviso-de-responsabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitadoresRoute = FacilitadoresRouteImport.update({
  id: '/facilitadores',
  path: '/facilitadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaModuloRoute = AcademiaModuloRouteImport.update({
  id: '/academia_/$modulo',
  path: '/academia/$modulo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasCategoriaRoute = ReceitasCategoriaRouteImport.update({
  id: '/receitas_/$categoria',
  path: '/receitas/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUaImageSplatRoute = ApiPublicUaImageSplatRouteImport.update({
  id: '/api/public/ua-image/$',
  path: '/api/public/ua-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUaVideoSplatRoute = ApiPublicUaVideoSplatRouteImport.update({
  id: '/api/public/ua-video/$',
  path: '/api/public/ua-video/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia/$modulo': typeof AcademiaModuloRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas/$categoria': typeof ReceitasCategoriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia/$modulo': typeof AcademiaModuloRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas/$categoria': typeof ReceitasCategoriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia_/$modulo': typeof AcademiaModuloRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas_/$categoria': typeof ReceitasCategoriaRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia/$modulo'
    | '/produto/$slug'
    | '/receitas/$categoria'
    | '/api/public/stripe-webhook'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia/$modulo'
    | '/produto/$slug'
    | '/receitas/$categoria'
    | '/api/public/stripe-webhook'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia_/$modulo'
    | '/produto/$slug'
    | '/receitas_/$categoria'
    | '/api/public/stripe-webhook'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AcademiaAtipicaRoute: typeof AcademiaAtipicaRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AssinaturaECancelamentoRoute: typeof AssinaturaECancelamentoRoute
  AvisoDeResponsabilidadeRoute: typeof AvisoDeResponsabilidadeRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CheckoutRoute: typeof CheckoutRoute
  ComunidadeRoute: typeof ComunidadeRoute
  EntrarRoute: typeof EntrarRoute
  FacilitadoresRoute: typeof FacilitadoresRoute
  ForumRoute: typeof ForumRoute
  InicioRoute: typeof InicioRoute
  MasterRoute: typeof MasterRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReceitasRoute: typeof ReceitasRoute
  TermosRoute: typeof TermosRoute
  VslRoute: typeof VslRoute
  AcademiaModuloRoute: typeof AcademiaModuloRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ReceitasCategoriaRoute: typeof ReceitasCategoriaRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicUaImageSplatRoute: typeof ApiPublicUaImageSplatRoute
  ApiPublicUaVideoSplatRoute: typeof ApiPublicUaVideoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia-atipica': {
      id: '/academia-atipica'
      path: '/academia-atipica'
      fullPath: '/academia-atipica'
      preLoaderRoute: typeof AcademiaAtipicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-e-cancelamento': {
      id: '/assinatura-e-cancelamento'
      path: '/assinatura-e-cancelamento'
      fullPath: '/assinatura-e-cancelamento'
      preLoaderRoute: typeof AssinaturaECancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-responsabilidade': {
      id: '/aviso-de-responsabilidade'
      path: '/aviso-de-responsabilidade'
      fullPath: '/aviso-de-responsabilidade'
      preLoaderRoute: typeof AvisoDeResponsabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitadores': {
      id: '/facilitadores'
      path: '/facilitadores'
      fullPath: '/facilitadores'
      preLoaderRoute: typeof FacilitadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia_/$modulo': {
      id: '/academia_/$modulo'
      path: '/academia/$modulo'
      fullPath: '/academia/$modulo'
      preLoaderRoute: typeof AcademiaModuloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas_/$categoria': {
      id: '/receitas_/$categoria'
      path: '/receitas/$categoria'
      fullPath: '/receitas/$categoria'
      preLoaderRoute: typeof ReceitasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ua-image/$': {
      id: '/api/public/ua-image/$'
      path: '/api/public/ua-image/$'
      fullPath: '/api/public/ua-image/$'
      preLoaderRoute: typeof ApiPublicUaImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ua-video/$': {
      id: '/api/public/ua-video/$'
      path: '/api/public/ua-video/$'
      fullPath: '/api/public/ua-video/$'
      preLoaderRoute: typeof ApiPublicUaVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AcademiaAtipicaRoute: AcademiaAtipicaRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  AssinaturaRoute: AssinaturaRoute,
  AssinaturaECancelamentoRoute: AssinaturaECancelamentoRoute,
  AvisoDeResponsabilidadeRoute: AvisoDeResponsabilidadeRoute,
  BibliotecaRoute: BibliotecaRoute,
  CheckoutRoute: CheckoutRoute,
  ComunidadeRoute: ComunidadeRoute,
  EntrarRoute: EntrarRoute,
  FacilitadoresRoute: FacilitadoresRoute,
  ForumRoute: ForumRoute,
  InicioRoute: InicioRoute,
  MasterRoute: MasterRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  ObrigadoRoute: ObrigadoRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReceitasRoute: ReceitasRoute,
  TermosRoute: TermosRoute,
  VslRoute: VslRoute,
  AcademiaModuloRoute: AcademiaModuloRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ReceitasCategoriaRoute: ReceitasCategoriaRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicUaImageSplatRoute: ApiPublicUaImageSplatRoute,
  ApiPublicUaVideoSplatRoute: ApiPublicUaVideoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
