/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as AcademiaAtipicaRouteImport } from './routes/academia-atipica'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AssinaturaECancelamentoRouteImport } from './routes/assinatura-e-cancelamento'
import { Route as AvisoDeResponsabilidadeRouteImport } from './routes/aviso-de-responsabilidade'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CamilaribeiroautismoRouteImport } from './routes/camilaribeiroautismo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FacilitadoresRouteImport } from './routes/facilitadores'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as NovaSenhaRouteImport } from './routes/nova-senha'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as AcademiaModuloRouteImport } from './routes/academia_.$modulo'
import { Route as GestaoComercialRouteImport } from './routes/gestao_.comercial'
import { Route as GestaoComunidadeRouteImport } from './routes/gestao_.comunidade'
import { Route as GestaoConteudosRouteImport } from './routes/gestao_.conteudos'
import { Route as GestaoPlataformaRouteImport } from './routes/gestao_.plataforma'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ReceitasCategoriaRouteImport } from './routes/receitas_.$categoria'
import { Route as ApiProtectedDriveVideoSplatRouteImport } from './routes/api/protected-drive-video/$'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as GestaoComercialCampanhasRouteImport } from './routes/gestao_.comercial_.campanhas'
import { Route as GestaoComercialConversoesRouteImport } from './routes/gestao_.comercial_.conversoes'
import { Route as GestaoComercialFunilRouteImport } from './routes/gestao_.comercial_.funil'
import { Route as GestaoComercialProdutosRouteImport } from './routes/gestao_.comercial_.produtos'
import { Route as GestaoComunidadeFacilitadoresRouteImport } from './routes/gestao_.comunidade_.facilitadores'
import { Route as GestaoComunidadeModeracaoRouteImport } from './routes/gestao_.comunidade_.moderacao'
import { Route as GestaoConteudosAcademiaRouteImport } from './routes/gestao_.conteudos_.academia'
import { Route as GestaoConteudosCategoriasRouteImport } from './routes/gestao_.conteudos_.categorias'
import { Route as GestaoConteudosImportacaoRouteImport } from './routes/gestao_.conteudos_.importacao'
import { Route as GestaoConteudosModulosRouteImport } from './routes/gestao_.conteudos_.modulos'
import { Route as GestaoConteudosReceitasRouteImport } from './routes/gestao_.conteudos_.receitas'
import { Route as GestaoPlataformaAcessosRouteImport } from './routes/gestao_.plataforma_.acessos'
import { Route as GestaoPlataformaAparenciaRouteImport } from './routes/gestao_.plataforma_.aparencia'
import { Route as ApiPublicUaImageSplatRouteImport } from './routes/api/public/ua-image/$'
import { Route as ApiPublicUaVideoSplatRouteImport } from './routes/api/public/ua-video/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaAtipicaRoute = AcademiaAtipicaRouteImport.update({
  id: '/academia-atipica',
  path: '/academia-atipica',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaECancelamentoRoute = AssinaturaECancelamentoRouteImport.update({
  id: '/assinatura-e-cancelamento',
  path: '/assinatura-e-cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeResponsabilidadeRoute = AvisoDeResponsabilidadeRouteImport.update({
  id: '/aviso-de-responsabilidade',
  path: '/aviso-de-responsabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CamilaribeiroautismoRoute = CamilaribeiroautismoRouteImport.update({
  id: '/camilaribeiroautismo',
  path: '/camilaribeiroautismo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitadoresRoute = FacilitadoresRouteImport.update({
  id: '/facilitadores',
  path: '/facilitadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaSenhaRoute = NovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaModuloRoute = AcademiaModuloRouteImport.update({
  id: '/academia_/$modulo',
  path: '/academia/$modulo',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoComercialRoute = GestaoComercialRouteImport.update({
  id: '/gestao_/comercial',
  path: '/gestao/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoComunidadeRoute = GestaoComunidadeRouteImport.update({
  id: '/gestao_/comunidade',
  path: '/gestao/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoConteudosRoute = GestaoConteudosRouteImport.update({
  id: '/gestao_/conteudos',
  path: '/gestao/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoPlataformaRoute = GestaoPlataformaRouteImport.update({
  id: '/gestao_/plataforma',
  path: '/gestao/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasCategoriaRoute = ReceitasCategoriaRouteImport.update({
  id: '/receitas_/$categoria',
  path: '/receitas/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectedDriveVideoSplatRoute =
  ApiProtectedDriveVideoSplatRouteImport.update({
    id: '/api/protected-drive-video/$',
    path: '/api/protected-drive-video/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoComercialCampanhasRoute =
  GestaoComercialCampanhasRouteImport.update({
    id: '/gestao_/comercial_/campanhas',
    path: '/gestao/comercial/campanhas',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoComercialConversoesRoute =
  GestaoComercialConversoesRouteImport.update({
    id: '/gestao_/comercial_/conversoes',
    path: '/gestao/comercial/conversoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoComercialFunilRoute = GestaoComercialFunilRouteImport.update({
  id: '/gestao_/comercial_/funil',
  path: '/gestao/comercial/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoComercialProdutosRoute = GestaoComercialProdutosRouteImport.update({
  id: '/gestao_/comercial_/produtos',
  path: '/gestao/comercial/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoComunidadeFacilitadoresRoute =
  GestaoComunidadeFacilitadoresRouteImport.update({
    id: '/gestao_/comunidade_/facilitadores',
    path: '/gestao/comunidade/facilitadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoComunidadeModeracaoRoute =
  GestaoComunidadeModeracaoRouteImport.update({
    id: '/gestao_/comunidade_/moderacao',
    path: '/gestao/comunidade/moderacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoConteudosAcademiaRoute = GestaoConteudosAcademiaRouteImport.update({
  id: '/gestao_/conteudos_/academia',
  path: '/gestao/conteudos/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoConteudosCategoriasRoute =
  GestaoConteudosCategoriasRouteImport.update({
    id: '/gestao_/conteudos_/categorias',
    path: '/gestao/conteudos/categorias',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoConteudosImportacaoRoute =
  GestaoConteudosImportacaoRouteImport.update({
    id: '/gestao_/conteudos_/importacao',
    path: '/gestao/conteudos/importacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const GestaoConteudosModulosRoute = GestaoConteudosModulosRouteImport.update({
  id: '/gestao_/conteudos_/modulos',
  path: '/gestao/conteudos/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoConteudosReceitasRoute = GestaoConteudosReceitasRouteImport.update({
  id: '/gestao_/conteudos_/receitas',
  path: '/gestao/conteudos/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoPlataformaAcessosRoute = GestaoPlataformaAcessosRouteImport.update({
  id: '/gestao_/plataforma_/acessos',
  path: '/gestao/plataforma/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoPlataformaAparenciaRoute =
  GestaoPlataformaAparenciaRouteImport.update({
    id: '/gestao_/plataforma_/aparencia',
    path: '/gestao/plataforma/aparencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUaImageSplatRoute = ApiPublicUaImageSplatRouteImport.update({
  id: '/api/public/ua-image/$',
  path: '/api/public/ua-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUaVideoSplatRoute = ApiPublicUaVideoSplatRouteImport.update({
  id: '/api/public/ua-video/$',
  path: '/api/public/ua-video/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/camilaribeiroautismo': typeof CamilaribeiroautismoRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/gestao': typeof GestaoRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia/$modulo': typeof AcademiaModuloRoute
  '/gestao/comercial': typeof GestaoComercialRoute
  '/gestao/comunidade': typeof GestaoComunidadeRoute
  '/gestao/conteudos': typeof GestaoConteudosRoute
  '/gestao/plataforma': typeof GestaoPlataformaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas/$categoria': typeof ReceitasCategoriaRoute
  '/api/protected-drive-video/$': typeof ApiProtectedDriveVideoSplatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/gestao/comercial/campanhas': typeof GestaoComercialCampanhasRoute
  '/gestao/comercial/conversoes': typeof GestaoComercialConversoesRoute
  '/gestao/comercial/funil': typeof GestaoComercialFunilRoute
  '/gestao/comercial/produtos': typeof GestaoComercialProdutosRoute
  '/gestao/comunidade/facilitadores': typeof GestaoComunidadeFacilitadoresRoute
  '/gestao/comunidade/moderacao': typeof GestaoComunidadeModeracaoRoute
  '/gestao/conteudos/academia': typeof GestaoConteudosAcademiaRoute
  '/gestao/conteudos/categorias': typeof GestaoConteudosCategoriasRoute
  '/gestao/conteudos/importacao': typeof GestaoConteudosImportacaoRoute
  '/gestao/conteudos/modulos': typeof GestaoConteudosModulosRoute
  '/gestao/conteudos/receitas': typeof GestaoConteudosReceitasRoute
  '/gestao/plataforma/acessos': typeof GestaoPlataformaAcessosRoute
  '/gestao/plataforma/aparencia': typeof GestaoPlataformaAparenciaRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/camilaribeiroautismo': typeof CamilaribeiroautismoRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/gestao': typeof GestaoRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia/$modulo': typeof AcademiaModuloRoute
  '/gestao/comercial': typeof GestaoComercialRoute
  '/gestao/comunidade': typeof GestaoComunidadeRoute
  '/gestao/conteudos': typeof GestaoConteudosRoute
  '/gestao/plataforma': typeof GestaoPlataformaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas/$categoria': typeof ReceitasCategoriaRoute
  '/api/protected-drive-video/$': typeof ApiProtectedDriveVideoSplatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/gestao/comercial/campanhas': typeof GestaoComercialCampanhasRoute
  '/gestao/comercial/conversoes': typeof GestaoComercialConversoesRoute
  '/gestao/comercial/funil': typeof GestaoComercialFunilRoute
  '/gestao/comercial/produtos': typeof GestaoComercialProdutosRoute
  '/gestao/comunidade/facilitadores': typeof GestaoComunidadeFacilitadoresRoute
  '/gestao/comunidade/moderacao': typeof GestaoComunidadeModeracaoRoute
  '/gestao/conteudos/academia': typeof GestaoConteudosAcademiaRoute
  '/gestao/conteudos/categorias': typeof GestaoConteudosCategoriasRoute
  '/gestao/conteudos/importacao': typeof GestaoConteudosImportacaoRoute
  '/gestao/conteudos/modulos': typeof GestaoConteudosModulosRoute
  '/gestao/conteudos/receitas': typeof GestaoConteudosReceitasRoute
  '/gestao/plataforma/acessos': typeof GestaoPlataformaAcessosRoute
  '/gestao/plataforma/aparencia': typeof GestaoPlataformaAparenciaRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/academia-atipica': typeof AcademiaAtipicaRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/assinatura': typeof AssinaturaRoute
  '/assinatura-e-cancelamento': typeof AssinaturaECancelamentoRoute
  '/aviso-de-responsabilidade': typeof AvisoDeResponsabilidadeRoute
  '/biblioteca': typeof BibliotecaRoute
  '/camilaribeiroautismo': typeof CamilaribeiroautismoRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/entrar': typeof EntrarRoute
  '/facilitadores': typeof FacilitadoresRoute
  '/forum': typeof ForumRoute
  '/gestao': typeof GestaoRoute
  '/inicio': typeof InicioRoute
  '/master': typeof MasterRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/nova-senha': typeof NovaSenhaRoute
  '/obrigado': typeof ObrigadoRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/receitas': typeof ReceitasRoute
  '/termos': typeof TermosRoute
  '/vsl': typeof VslRoute
  '/academia_/$modulo': typeof AcademiaModuloRoute
  '/gestao_/comercial': typeof GestaoComercialRoute
  '/gestao_/comunidade': typeof GestaoComunidadeRoute
  '/gestao_/conteudos': typeof GestaoConteudosRoute
  '/gestao_/plataforma': typeof GestaoPlataformaRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/receitas_/$categoria': typeof ReceitasCategoriaRoute
  '/api/protected-drive-video/$': typeof ApiProtectedDriveVideoSplatRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/gestao_/comercial_/campanhas': typeof GestaoComercialCampanhasRoute
  '/gestao_/comercial_/conversoes': typeof GestaoComercialConversoesRoute
  '/gestao_/comercial_/funil': typeof GestaoComercialFunilRoute
  '/gestao_/comercial_/produtos': typeof GestaoComercialProdutosRoute
  '/gestao_/comunidade_/facilitadores': typeof GestaoComunidadeFacilitadoresRoute
  '/gestao_/comunidade_/moderacao': typeof GestaoComunidadeModeracaoRoute
  '/gestao_/conteudos_/academia': typeof GestaoConteudosAcademiaRoute
  '/gestao_/conteudos_/categorias': typeof GestaoConteudosCategoriasRoute
  '/gestao_/conteudos_/importacao': typeof GestaoConteudosImportacaoRoute
  '/gestao_/conteudos_/modulos': typeof GestaoConteudosModulosRoute
  '/gestao_/conteudos_/receitas': typeof GestaoConteudosReceitasRoute
  '/gestao_/plataforma_/acessos': typeof GestaoPlataformaAcessosRoute
  '/gestao_/plataforma_/aparencia': typeof GestaoPlataformaAparenciaRoute
  '/api/public/ua-image/$': typeof ApiPublicUaImageSplatRoute
  '/api/public/ua-video/$': typeof ApiPublicUaVideoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/camilaribeiroautismo'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/gestao'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia/$modulo'
    | '/gestao/comercial'
    | '/gestao/comunidade'
    | '/gestao/conteudos'
    | '/gestao/plataforma'
    | '/produto/$slug'
    | '/receitas/$categoria'
    | '/api/protected-drive-video/$'
    | '/api/public/stripe-webhook'
    | '/gestao/comercial/campanhas'
    | '/gestao/comercial/conversoes'
    | '/gestao/comercial/funil'
    | '/gestao/comercial/produtos'
    | '/gestao/comunidade/facilitadores'
    | '/gestao/comunidade/moderacao'
    | '/gestao/conteudos/academia'
    | '/gestao/conteudos/categorias'
    | '/gestao/conteudos/importacao'
    | '/gestao/conteudos/modulos'
    | '/gestao/conteudos/receitas'
    | '/gestao/plataforma/acessos'
    | '/gestao/plataforma/aparencia'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/camilaribeiroautismo'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/gestao'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia/$modulo'
    | '/gestao/comercial'
    | '/gestao/comunidade'
    | '/gestao/conteudos'
    | '/gestao/plataforma'
    | '/produto/$slug'
    | '/receitas/$categoria'
    | '/api/protected-drive-video/$'
    | '/api/public/stripe-webhook'
    | '/gestao/comercial/campanhas'
    | '/gestao/comercial/conversoes'
    | '/gestao/comercial/funil'
    | '/gestao/comercial/produtos'
    | '/gestao/comunidade/facilitadores'
    | '/gestao/comunidade/moderacao'
    | '/gestao/conteudos/academia'
    | '/gestao/conteudos/categorias'
    | '/gestao/conteudos/importacao'
    | '/gestao/conteudos/modulos'
    | '/gestao/conteudos/receitas'
    | '/gestao/plataforma/acessos'
    | '/gestao/plataforma/aparencia'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/academia-atipica'
    | '/admin'
    | '/ajuda'
    | '/assinatura'
    | '/assinatura-e-cancelamento'
    | '/aviso-de-responsabilidade'
    | '/biblioteca'
    | '/camilaribeiroautismo'
    | '/checkout'
    | '/comunidade'
    | '/entrar'
    | '/facilitadores'
    | '/forum'
    | '/gestao'
    | '/inicio'
    | '/master'
    | '/minha-assinatura'
    | '/nova-senha'
    | '/obrigado'
    | '/perfil'
    | '/privacidade'
    | '/receitas'
    | '/termos'
    | '/vsl'
    | '/academia_/$modulo'
    | '/gestao_/comercial'
    | '/gestao_/comunidade'
    | '/gestao_/conteudos'
    | '/gestao_/plataforma'
    | '/produto/$slug'
    | '/receitas_/$categoria'
    | '/api/protected-drive-video/$'
    | '/api/public/stripe-webhook'
    | '/gestao_/comercial_/campanhas'
    | '/gestao_/comercial_/conversoes'
    | '/gestao_/comercial_/funil'
    | '/gestao_/comercial_/produtos'
    | '/gestao_/comunidade_/facilitadores'
    | '/gestao_/comunidade_/moderacao'
    | '/gestao_/conteudos_/academia'
    | '/gestao_/conteudos_/categorias'
    | '/gestao_/conteudos_/importacao'
    | '/gestao_/conteudos_/modulos'
    | '/gestao_/conteudos_/receitas'
    | '/gestao_/plataforma_/acessos'
    | '/gestao_/plataforma_/aparencia'
    | '/api/public/ua-image/$'
    | '/api/public/ua-video/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AcademiaAtipicaRoute: typeof AcademiaAtipicaRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AssinaturaECancelamentoRoute: typeof AssinaturaECancelamentoRoute
  AvisoDeResponsabilidadeRoute: typeof AvisoDeResponsabilidadeRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CamilaribeiroautismoRoute: typeof CamilaribeiroautismoRoute
  CheckoutRoute: typeof CheckoutRoute
  ComunidadeRoute: typeof ComunidadeRoute
  EntrarRoute: typeof EntrarRoute
  FacilitadoresRoute: typeof FacilitadoresRoute
  ForumRoute: typeof ForumRoute
  GestaoRoute: typeof GestaoRoute
  InicioRoute: typeof InicioRoute
  MasterRoute: typeof MasterRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  NovaSenhaRoute: typeof NovaSenhaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReceitasRoute: typeof ReceitasRoute
  TermosRoute: typeof TermosRoute
  VslRoute: typeof VslRoute
  AcademiaModuloRoute: typeof AcademiaModuloRoute
  GestaoComercialRoute: typeof GestaoComercialRoute
  GestaoComunidadeRoute: typeof GestaoComunidadeRoute
  GestaoConteudosRoute: typeof GestaoConteudosRoute
  GestaoPlataformaRoute: typeof GestaoPlataformaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ReceitasCategoriaRoute: typeof ReceitasCategoriaRoute
  ApiProtectedDriveVideoSplatRoute: typeof ApiProtectedDriveVideoSplatRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  GestaoComercialCampanhasRoute: typeof GestaoComercialCampanhasRoute
  GestaoComercialConversoesRoute: typeof GestaoComercialConversoesRoute
  GestaoComercialFunilRoute: typeof GestaoComercialFunilRoute
  GestaoComercialProdutosRoute: typeof GestaoComercialProdutosRoute
  GestaoComunidadeFacilitadoresRoute: typeof GestaoComunidadeFacilitadoresRoute
  GestaoComunidadeModeracaoRoute: typeof GestaoComunidadeModeracaoRoute
  GestaoConteudosAcademiaRoute: typeof GestaoConteudosAcademiaRoute
  GestaoConteudosCategoriasRoute: typeof GestaoConteudosCategoriasRoute
  GestaoConteudosImportacaoRoute: typeof GestaoConteudosImportacaoRoute
  GestaoConteudosModulosRoute: typeof GestaoConteudosModulosRoute
  GestaoConteudosReceitasRoute: typeof GestaoConteudosReceitasRoute
  GestaoPlataformaAcessosRoute: typeof GestaoPlataformaAcessosRoute
  GestaoPlataformaAparenciaRoute: typeof GestaoPlataformaAparenciaRoute
  ApiPublicUaImageSplatRoute: typeof ApiPublicUaImageSplatRoute
  ApiPublicUaVideoSplatRoute: typeof ApiPublicUaVideoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia-atipica': {
      id: '/academia-atipica'
      path: '/academia-atipica'
      fullPath: '/academia-atipica'
      preLoaderRoute: typeof AcademiaAtipicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-e-cancelamento': {
      id: '/assinatura-e-cancelamento'
      path: '/assinatura-e-cancelamento'
      fullPath: '/assinatura-e-cancelamento'
      preLoaderRoute: typeof AssinaturaECancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-responsabilidade': {
      id: '/aviso-de-responsabilidade'
      path: '/aviso-de-responsabilidade'
      fullPath: '/aviso-de-responsabilidade'
      preLoaderRoute: typeof AvisoDeResponsabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camilaribeiroautismo': {
      id: '/camilaribeiroautismo'
      path: '/camilaribeiroautismo'
      fullPath: '/camilaribeiroautismo'
      preLoaderRoute: typeof CamilaribeiroautismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilitadores': {
      id: '/facilitadores'
      path: '/facilitadores'
      fullPath: '/facilitadores'
      preLoaderRoute: typeof FacilitadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-senha': {
      id: '/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof NovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia_/$modulo': {
      id: '/academia_/$modulo'
      path: '/academia/$modulo'
      fullPath: '/academia/$modulo'
      preLoaderRoute: typeof AcademiaModuloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comercial': {
      id: '/gestao_/comercial'
      path: '/gestao/comercial'
      fullPath: '/gestao/comercial'
      preLoaderRoute: typeof GestaoComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comunidade': {
      id: '/gestao_/comunidade'
      path: '/gestao/comunidade'
      fullPath: '/gestao/comunidade'
      preLoaderRoute: typeof GestaoComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos': {
      id: '/gestao_/conteudos'
      path: '/gestao/conteudos'
      fullPath: '/gestao/conteudos'
      preLoaderRoute: typeof GestaoConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/plataforma': {
      id: '/gestao_/plataforma'
      path: '/gestao/plataforma'
      fullPath: '/gestao/plataforma'
      preLoaderRoute: typeof GestaoPlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas_/$categoria': {
      id: '/receitas_/$categoria'
      path: '/receitas/$categoria'
      fullPath: '/receitas/$categoria'
      preLoaderRoute: typeof ReceitasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protected-drive-video/$': {
      id: '/api/protected-drive-video/$'
      path: '/api/protected-drive-video/$'
      fullPath: '/api/protected-drive-video/$'
      preLoaderRoute: typeof ApiProtectedDriveVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comercial_/campanhas': {
      id: '/gestao_/comercial_/campanhas'
      path: '/gestao/comercial/campanhas'
      fullPath: '/gestao/comercial/campanhas'
      preLoaderRoute: typeof GestaoComercialCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comercial_/conversoes': {
      id: '/gestao_/comercial_/conversoes'
      path: '/gestao/comercial/conversoes'
      fullPath: '/gestao/comercial/conversoes'
      preLoaderRoute: typeof GestaoComercialConversoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comercial_/funil': {
      id: '/gestao_/comercial_/funil'
      path: '/gestao/comercial/funil'
      fullPath: '/gestao/comercial/funil'
      preLoaderRoute: typeof GestaoComercialFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comercial_/produtos': {
      id: '/gestao_/comercial_/produtos'
      path: '/gestao/comercial/produtos'
      fullPath: '/gestao/comercial/produtos'
      preLoaderRoute: typeof GestaoComercialProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comunidade_/facilitadores': {
      id: '/gestao_/comunidade_/facilitadores'
      path: '/gestao/comunidade/facilitadores'
      fullPath: '/gestao/comunidade/facilitadores'
      preLoaderRoute: typeof GestaoComunidadeFacilitadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/comunidade_/moderacao': {
      id: '/gestao_/comunidade_/moderacao'
      path: '/gestao/comunidade/moderacao'
      fullPath: '/gestao/comunidade/moderacao'
      preLoaderRoute: typeof GestaoComunidadeModeracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos_/academia': {
      id: '/gestao_/conteudos_/academia'
      path: '/gestao/conteudos/academia'
      fullPath: '/gestao/conteudos/academia'
      preLoaderRoute: typeof GestaoConteudosAcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos_/categorias': {
      id: '/gestao_/conteudos_/categorias'
      path: '/gestao/conteudos/categorias'
      fullPath: '/gestao/conteudos/categorias'
      preLoaderRoute: typeof GestaoConteudosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos_/importacao': {
      id: '/gestao_/conteudos_/importacao'
      path: '/gestao/conteudos/importacao'
      fullPath: '/gestao/conteudos/importacao'
      preLoaderRoute: typeof GestaoConteudosImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos_/modulos': {
      id: '/gestao_/conteudos_/modulos'
      path: '/gestao/conteudos/modulos'
      fullPath: '/gestao/conteudos/modulos'
      preLoaderRoute: typeof GestaoConteudosModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/conteudos_/receitas': {
      id: '/gestao_/conteudos_/receitas'
      path: '/gestao/conteudos/receitas'
      fullPath: '/gestao/conteudos/receitas'
      preLoaderRoute: typeof GestaoConteudosReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/plataforma_/acessos': {
      id: '/gestao_/plataforma_/acessos'
      path: '/gestao/plataforma/acessos'
      fullPath: '/gestao/plataforma/acessos'
      preLoaderRoute: typeof GestaoPlataformaAcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao_/plataforma_/aparencia': {
      id: '/gestao_/plataforma_/aparencia'
      path: '/gestao/plataforma/aparencia'
      fullPath: '/gestao/plataforma/aparencia'
      preLoaderRoute: typeof GestaoPlataformaAparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ua-image/$': {
      id: '/api/public/ua-image/$'
      path: '/api/public/ua-image/$'
      fullPath: '/api/public/ua-image/$'
      preLoaderRoute: typeof ApiPublicUaImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ua-video/$': {
      id: '/api/public/ua-video/$'
      path: '/api/public/ua-video/$'
      fullPath: '/api/public/ua-video/$'
      preLoaderRoute: typeof ApiPublicUaVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AcademiaAtipicaRoute: AcademiaAtipicaRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  AssinaturaRoute: AssinaturaRoute,
  AssinaturaECancelamentoRoute: AssinaturaECancelamentoRoute,
  AvisoDeResponsabilidadeRoute: AvisoDeResponsabilidadeRoute,
  BibliotecaRoute: BibliotecaRoute,
  CamilaribeiroautismoRoute: CamilaribeiroautismoRoute,
  CheckoutRoute: CheckoutRoute,
  ComunidadeRoute: ComunidadeRoute,
  EntrarRoute: EntrarRoute,
  FacilitadoresRoute: FacilitadoresRoute,
  ForumRoute: ForumRoute,
  GestaoRoute: GestaoRoute,
  InicioRoute: InicioRoute,
  MasterRoute: MasterRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  NovaSenhaRoute: NovaSenhaRoute,
  ObrigadoRoute: ObrigadoRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReceitasRoute: ReceitasRoute,
  TermosRoute: TermosRoute,
  VslRoute: VslRoute,
  AcademiaModuloRoute: AcademiaModuloRoute,
  GestaoComercialRoute: GestaoComercialRoute,
  GestaoComunidadeRoute: GestaoComunidadeRoute,
  GestaoConteudosRoute: GestaoConteudosRoute,
  GestaoPlataformaRoute: GestaoPlataformaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ReceitasCategoriaRoute: ReceitasCategoriaRoute,
  ApiProtectedDriveVideoSplatRoute: ApiProtectedDriveVideoSplatRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  GestaoComercialCampanhasRoute: GestaoComercialCampanhasRoute,
  GestaoComercialConversoesRoute: GestaoComercialConversoesRoute,
  GestaoComercialFunilRoute: GestaoComercialFunilRoute,
  GestaoComercialProdutosRoute: GestaoComercialProdutosRoute,
  GestaoComunidadeFacilitadoresRoute: GestaoComunidadeFacilitadoresRoute,
  GestaoComunidadeModeracaoRoute: GestaoComunidadeModeracaoRoute,
  GestaoConteudosAcademiaRoute: GestaoConteudosAcademiaRoute,
  GestaoConteudosCategoriasRoute: GestaoConteudosCategoriasRoute,
  GestaoConteudosImportacaoRoute: GestaoConteudosImportacaoRoute,
  GestaoConteudosModulosRoute: GestaoConteudosModulosRoute,
  GestaoConteudosReceitasRoute: GestaoConteudosReceitasRoute,
  GestaoPlataformaAcessosRoute: GestaoPlataformaAcessosRoute,
  GestaoPlataformaAparenciaRoute: GestaoPlataformaAparenciaRoute,
  ApiPublicUaImageSplatRoute: ApiPublicUaImageSplatRoute,
  ApiPublicUaVideoSplatRoute: ApiPublicUaVideoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
