BEGIN;
-- Reuse the original product/resource IDs and assets. No copy, rename or deletion.
CREATE TABLE IF NOT EXISTS public.ua_store_collections (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL, slug text NOT NULL UNIQUE,
 kind text NOT NULL CHECK (kind IN ('category','collection')),
 description text NOT NULL DEFAULT '', image_url text NOT NULL DEFAULT '',
 position integer NOT NULL DEFAULT 0,
 status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
 featured boolean NOT NULL DEFAULT false,
 updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ua_store_collections ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ua_store_collections TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ua_store_collections_id_seq TO service_role;

ALTER TABLE public.ua_facilitators
 ADD COLUMN IF NOT EXISTS slug text,
 ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES public.ua_store_collections(id),
 ADD COLUMN IF NOT EXISTS collection_ids bigint[] NOT NULL DEFAULT '{}',
 ADD COLUMN IF NOT EXISTS price_cents integer CHECK (price_cents >= 0),
 ADD COLUMN IF NOT EXISTS sale_price_cents integer CHECK (sale_price_cents >= 0),
 ADD COLUMN IF NOT EXISTS visible_public boolean NOT NULL DEFAULT false,
 ADD COLUMN IF NOT EXISTS visible_members boolean NOT NULL DEFAULT true,
 ADD COLUMN IF NOT EXISTS shop_details jsonb NOT NULL DEFAULT '{}';
ALTER TABLE public.ua_facilitators ADD COLUMN IF NOT EXISTS store_price_cents integer GENERATED ALWAYS AS (coalesce(sale_price_cents,price_cents)) STORED;
UPDATE public.ua_facilitators SET slug = 'produto-' || id WHERE slug IS NULL;
ALTER TABLE public.ua_facilitators ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ua_facilitators_slug_unique ON public.ua_facilitators(slug);
CREATE INDEX IF NOT EXISTS ua_facilitators_shop_listing ON public.ua_facilitators(status, visible_public, category_id, position);
CREATE INDEX IF NOT EXISTS ua_facilitators_collections_gin ON public.ua_facilitators USING gin(collection_ids);

INSERT INTO public.ua_store_collections(name,slug,kind,status)
 SELECT DISTINCT category, 'categoria-' || substr(md5(category),1,12), 'category','published'
 FROM public.ua_facilitators WHERE trim(category) <> ''
 ON CONFLICT (slug) DO NOTHING;
UPDATE public.ua_facilitators f SET category_id=c.id
 FROM public.ua_store_collections c
 WHERE c.kind='category' AND c.name=f.category AND f.category_id IS NULL;

CREATE TABLE IF NOT EXISTS public.ua_store_settings (
 id integer PRIMARY KEY CHECK (id=1),
 settings jsonb NOT NULL DEFAULT '{}',
 updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ua_store_settings ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.ua_store_settings TO service_role;
INSERT INTO public.ua_store_settings(id) VALUES(1) ON CONFLICT DO NOTHING;
-- No anon/authenticated grants or permissive RLS policy. Public reads are
-- whitelisted and filtered by the server; publication remains an admin decision.
COMMIT;
